-- 난방 마스터 시공사례 CMS 설치 SQL
-- Supabase > SQL Editor > New query에서 이 파일 전체를 한 번 실행하세요.

create extension if not exists pgcrypto;

create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  category text not null check (category in ('excavation', 'heating', 'plumbing', 'leak')),
  title text not null,
  summary text not null default '',
  description text not null default '',
  region text not null default '서울 · 인천 · 경기',
  work_details text not null default '',
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.project_images (
  id bigint generated by default as identity primary key,
  project_id uuid not null references public.projects(id) on delete cascade,
  image_url text not null,
  storage_path text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists projects_category_created_idx
  on public.projects(category, created_at desc);

create index if not exists project_images_project_sort_idx
  on public.project_images(project_id, sort_order);

alter table public.projects enable row level security;
alter table public.project_images enable row level security;

drop policy if exists "public can read published projects" on public.projects;
drop policy if exists "admin can manage projects" on public.projects;
drop policy if exists "public can read published project images" on public.project_images;
drop policy if exists "admin can manage project images" on public.project_images;

create policy "public can read published projects"
on public.projects
for select
using (
  is_published = true
  or (auth.jwt() ->> 'email') = 'nbmaster1223@naver.com'
);

create policy "admin can manage projects"
on public.projects
for all
using ((auth.jwt() ->> 'email') = 'nbmaster1223@naver.com')
with check ((auth.jwt() ->> 'email') = 'nbmaster1223@naver.com');

create policy "public can read published project images"
on public.project_images
for select
using (
  exists (
    select 1
    from public.projects
    where projects.id = project_images.project_id
      and (
        projects.is_published = true
        or (auth.jwt() ->> 'email') = 'nbmaster1223@naver.com'
      )
  )
);

create policy "admin can manage project images"
on public.project_images
for all
using ((auth.jwt() ->> 'email') = 'nbmaster1223@naver.com')
with check ((auth.jwt() ->> 'email') = 'nbmaster1223@naver.com');

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'project-images',
  'project-images',
  true,
  15728640,
  array['image/jpeg','image/png','image/webp','image/gif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "public can view project images" on storage.objects;
drop policy if exists "admin can upload project images" on storage.objects;
drop policy if exists "admin can update project images" on storage.objects;
drop policy if exists "admin can delete project images" on storage.objects;

create policy "public can view project images"
on storage.objects
for select
using (bucket_id = 'project-images');

create policy "admin can upload project images"
on storage.objects
for insert
with check (
  bucket_id = 'project-images'
  and (auth.jwt() ->> 'email') = 'nbmaster1223@naver.com'
);

create policy "admin can update project images"
on storage.objects
for update
using (
  bucket_id = 'project-images'
  and (auth.jwt() ->> 'email') = 'nbmaster1223@naver.com'
)
with check (
  bucket_id = 'project-images'
  and (auth.jwt() ->> 'email') = 'nbmaster1223@naver.com'
);

create policy "admin can delete project images"
on storage.objects
for delete
using (
  bucket_id = 'project-images'
  and (auth.jwt() ->> 'email') = 'nbmaster1223@naver.com'
);
